apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ankii1212/mern-application-backend
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/budhan-users"
          ports:
            - containerPort: 5000
